name: Deploy to Firebase

on:
  push:
    branches:
      - master  # or your preferred branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project lankacalc
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
